apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: toorak-lending-monitor
  namespace: monitoring
  labels:
    release: prometheus
    app: toorak-lending-api
spec:
  selector:
    matchLabels:
      app: toorak-lending-api
  namespaceSelector:
    matchNames:
      - finacplus-dev
      - finacplus-staging
      - finacplus-prod
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
