apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finacplus-dev

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: toorak-lending-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
